version: 2.1

jobs:
    Test:
        docker:
            - image: pyne/ubuntu_18.04_py2_dagmc_pymoab_pyne-deps
        steps:
            - checkout
            - run: apt-get install -y python-pip
            - run: pip install pytest
            - run: pytest

workflows:
    build:
        jobs:
            - Test
