version: 2.1

jobs:
    Test:
        docker:
            - image: piperlincoln/dagmc-viz-ubuntu18.04:v0.2
        steps:
            - checkout
            - run: pytest

workflows:
    build:
        jobs:
            - Test
