version: 2.1

jobs:
    Test:
        docker:
            - image: svalinn/pymoab-visit-py2-18.04
              auth:
                username: $DOCKERHUB_USER
                password: $DOCKERHUB_PASS
        steps:
            - checkout
            - run: pytest

workflows:
    build:
        jobs:
            - Test:
                context: dockerhub
