version: 2.1

jobs:
    Test:
        docker:
            - image: pyne/pyne_ubuntu_16.04
        steps:
            - checkout
            - run: pip install pytest
            - run: pytest

workflows:
    build:
        jobs:
            - Test
