version: 2.1

jobs:
    Test:
        docker:
            - image: pyne/ubuntu_18.04_py2_dagmc_pymoab_pyne-deps
        steps:
            - checkout
            - run: apt-get install -y python-pip
            - run: pip install pytest
            - run: pytest Testing/Tests/graveyard_removal_test.py
            - run: pytest Testing/Tests/tag_expansion_test.py
            - store_test_results:
                path: test-results

workflows:
    build:
        jobs:
            - Test
