version: 2.1


executors:
    snippets:
        docker:
            - image: pyne/pyne_ubuntu_18.04

jobs:
    testing:
        executor:
            name: testing
        steps:
            - run: pytest
