version: 2.1

jobs:
    Test:
        docker:
            - image: pyne/ubuntu_18.04_py2_dagmc_pymoab_pyne-deps
        steps:
            - checkout
            - run: cd $HOME/opt
            - run: wget http://portal.nersc.gov/project/visit/releases/2.13.2/visit2_13_2.linux-x86_64-ubuntu14.tar.gz
            - run: wget http://portal.nersc.gov/project/visit/releases/2.13.2/visit-install2_13_2
            - run: echo 1 > input
            - run: bash visit-install2_13_2 2.13.2 linux-x86_64-ubuntu14 /usr/local/visit < input
            - run: echo 'export PATH=/usr/local/visit/visit2_13_3.linux-x86_64/bin:$PATH' >> $HOME/.bashrc
            - run: echo 'export LD_LIBRARY_PATH=/usr/local/visit/2.13.2/linux-x86_64/lib/:$LD_LIBRARY_PATH' >> $HOME/.bashrc
            - run: echo 'export PYTHONPATH=/usr/local/visit/2.13.2/linux-x86_64/lib/site-packages:$PYTHONPATH' >> $HOME/.bashrc
            - run: apt-get install -y python-pip
            - run: pip install pytest
            - run: ls input
            - run: pytest Testing/Tests/graveyard_removal_test.py
            - run: pytest Testing/Tests/tag_expansion_test.py

workflows:
    build:
        jobs:
            - Test
