version: 2.1

jobs:
    Test:
        docker:
            - image: piperlincoln/pytest-ubuntu18.04:v0.2
        steps:
            - checkout
            - run: pip install pytest
            - run: pytest
            - run: ls

workflows:
    build:
        jobs:
            - Test
